{ config, pkgs, settings, ... }:

let 
  home = builtins.getEnv "HOME";
in { 
  imports = [
    # generated by install script
    ../hardware/vmware-fusion.nix
    ../nixos
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = config.settings.hostname;
  networking.networkmanager.enable = true;
  networking.firewall.enable = false;

  sound.enable = true;
  hardware.pulseaudio.enable = true;

  services.xserver.enable = true;
  services.xserver.desktopManager.xterm.enable = false;
  services.xserver.displayManager.defaultSession = "none+i3";
  services.xserver.windowManager.i3.enable = true;
  services.xserver.autorun = true;
  services.xserver.autoRepeatDelay = 250;
  services.xserver.dpi = 140;

  hardware.video.hidpi.enable = true;

  virtualisation.vmware.guest.enable = true;
  virtualisation.docker.enable = true;
  virtualisation.docker.enableOnBoot = false;
  services.logind.extraConfig = ''
    RuntimeDirectorySize=8G
  '';

  fonts.fonts = with pkgs; [
    corefonts
    inconsolata
    libertine
    libre-baskerville
  ];

  users.users.${config.settings.username} = {
    isNormalUser = true;
    createHome = true;
    home = "/home/${config.settings.username}";
    description = "${config.settings.description}";
    extraGroups = [ "audio" "sound" "video" "docker" "networkmanager" "wheel" ];
    uid = 1000;
    shell = pkgs.zsh;
  };

  home-manager.users.${config.settings.username} = {
    home = {
      packages = with pkgs; [
        alacritty
        bitwarden
        brave
        delta
        docker
        dotnet-sdk
        drawio
        feh
        ffmpeg
        gimp
        inkscape
        mpv
        nodejs
        pavucontrol
        python39
        rclone
        rustup
        spotify-qt
        visual-studio-code
        yarn2nix
        yarn
      ];
    };

    xsession.enable = true;

    programs.emacs.enable = true;
    services.emacs.enable = true;

    programs.zsh.shellInit = ''
      if [[ -n "$(command -v dotnet)" ]]; then
        export PATH=${home}/.dotnet/tools:$PATH
        export DOTNET_PATH=$(nix-store -q --references $(which dotnet) | grep dotnet | head)
      fi

      if [[ -n "$(command -v cargo)" ]]; then
        export PATH=${home}/.cargo/bin:$PATH
      fi

      function setup_vim() {
        if [[ -n "$(command -v vim)" ]]; then
          if [[ ! -f "$HOME/.vim/autoload/plug.vim" ]]; then
            echo "Installing Vim Plug..."
            curl -Lo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
          fi

          if [[ ! -d "$HOME/.vim/plugged" ]]; then
            echo "Installing Vim plugins..."
            vim +'PlugInstall --sync' +qa
          fi
        fi
      }

      function pclone() {
        GIT_REPO=tjmaynes/$1

        if [[ -z "$1" ]]; then
          echo "Please provide a git repo as arg 1"  
        elif [[ ! -d "$WORKSPACE_DIR/$GIT_REPO" ]]; then
          git clone git@github.com:$GIT_REPO.git $WORKSPACE_DIR/$GIT_REPO

          [[ -d "$WORKSPACE_DIR/$GIT_REPO" ]] && cd $WORKSPACE_DIR/$GIT_REPO
        fi
      }

      setup_vim
    '';

  };
}
